### ISSUE TITLE
关于view-custom-form相关疑问

### ISSUE THREAD

**Issue by solomist** [aisuda/uview-custom-form#1]
作者你好 
请问文档中提及uview自定义组件模板，uniapp + uview 技术栈，用于开发APP和各类小程序自定义组件（默认支持uview ui库）。
这里的默认支持uview ui 是指的爱速搭平台支持了uview ui 而不是只amis本身支持是吧
如果使用的是amis本身的sdk模式想要支持uview 类似的ui库需要自己一个一个重新自定义吗？
请问我的理解正确吗

**Comment by wibetter** [comment]
@solomist [uview-custom-form](https://github.com/aisuda/uview-custom-form)自定义组件模板 目前主要用于开发小程序自定义组件的，用的不是amis渲染器。
如果你想支持 uview 类似的ui库，需要参照vue技术栈自定义组件模板（比如 [vue2-amis-custom-widget](https://github.com/aisuda/amis-widget-cli/tree/master/src/template/vue2-amis-custom-widget)）一个个自己封装才行。
